name: Scheduled generate and commit M3U

on:
  schedule:
    # To run at 02:58, 08:58, 14:58, 20:58 Europe/Athens local time regardless of DST, include both UTC offsets.
    - cron: '58 23,5,11,17 * * *'  # covers Athens = UTC+3 (EEST) -> 02:58,08:58,14:58,20:58
    - cron: '58 0,6,12,18 * * *'   # covers Athens = UTC+2 (EET)  -> 02:58,08:58,14:58,20:58
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U yt-dlp tqdm termcolor

      - name: Run generator script
        run: |
          python generate_m3u_youtube.py -i youtube_urls.txt -o youtube_streams.m3u -c settings.json

      - name: Commit files if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add youtube_streams.m3u settings.json
            git commit -m "autoupdate: regenerate youtube_streams.m3u (scheduled run)" || true
            git push
          else
            echo "No changes to commit"
          fi
